/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module pattern_detection(clk_i, reset_i, data_i, match_o);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  input clk_i;
  wire [2:0] curr_state;
  input data_i;
  output match_o;
  input reset_i;
  INV_X1 _10_ (
    .A(curr_state[2]),
    .ZN(_06_)
  );
  INV_X1 _11_ (
    .A(curr_state[0]),
    .ZN(_03_)
  );
  INV_X1 _12_ (
    .A(curr_state[1]),
    .ZN(_04_)
  );
  OAI21_X1 _13_ (
    .A(_04_),
    .B1(data_i),
    .B2(_03_),
    .ZN(_02_)
  );
  AND2_X1 _14_ (
    .A1(curr_state[1]),
    .A2(data_i),
    .ZN(match_o)
  );
  OAI21_X1 _15_ (
    .A(data_i),
    .B1(curr_state[0]),
    .B2(curr_state[2]),
    .ZN(_05_)
  );
  INV_X1 _16_ (
    .A(_05_),
    .ZN(_01_)
  );
  NOR2_X1 _17_ (
    .A1(_06_),
    .A2(data_i),
    .ZN(_00_)
  );
  DFFS_X1 _18_ (
    .CK(clk_i),
    .D(_02_),
    .Q(curr_state[0]),
    .QN(_07_),
    .SN(reset_i)
  );
  DFFR_X1 _19_ (
    .CK(clk_i),
    .D(_00_),
    .Q(curr_state[1]),
    .QN(_08_),
    .RN(reset_i)
  );
  DFFR_X1 _20_ (
    .CK(clk_i),
    .D(_01_),
    .Q(curr_state[2]),
    .QN(_09_),
    .RN(reset_i)
  );
endmodule
